### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [baidu/Senta#1]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [SentiClsDnn::global_destroy](https://github.com/baidu/Senta/blob/77664e9b08c19a6a6fdcf013cf164c2603a1753b/C-API/senti_cls_dnn.cpp#L63 "SentiClsDnn::global_destroy function")
- [WordSegment::thread_destroy](https://github.com/baidu/Senta/blob/77664e9b08c19a6a6fdcf013cf164c2603a1753b/C-API/wordseg.cpp#L48 "WordSegment::thread_destroy function")

**Comment by csaimd** [comment]
eval的时候有问题，
for data in test_reader():
            # infer a batch
            pred = exe.run(inference_program,
                feed=utils.data2tensor(data, place),
                fetch_list=fetch_targets,
                return_numpy=True)
            for i, val in enumerate(data):
                class3_label, class2_label = utils.get_predict_label(pred[0][i, 1])
                true_label = val[1]
                if class2_label == true_label:
                    class2_acc += 1
                if class3_label == true_label:
                    class3_acc += 1
                if true_label == 1.0:
                    neu_count += 1

            total_count += len(data)

        class2_acc = class2_acc / (total_count - neu_count)
        class3_acc = class3_acc / total_count
为什么for循环进不去，直接跑到class2_acc = class2_acc / (total_count - neu_count)
        class3_acc = class3_acc / total_count，然后除数为零，就出问题了

**Comment by ChinaLiuHao** [comment]
test_reader()里是否塞数据了呢？

**Comment by csaimd** [comment]
解决了，batchsize在测试的时候设置为1，然后就好了

**Comment by csaimd** [comment]
默认batchsize=256，但是测试的例子中只有200条数据
