### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by yuppx** [baidu/Senta#2]
编译lac模块
克隆lac代码，修改Makefile

cd fluid_install_dir/third_party/install/
git clone https://github.com/baidu/lac

修改CMakeList.txt, 将:
SET(PADDLE_ROOT ../../../fluid_install_dir)
改为
SET(PADDLE_ROOT 你的PaddlePaddle Fluid Inference部署路径)

修改哪个文件夹下的cmakelist.txt?  在lac文件夹下的cmakelist.txt中没有找到SET(PADDLE_ROOT ../../../fluid_install_dir)这一句

**Comment by ChinaLiuHao** [comment]
这里可以参考baidu/lac最新的安装编译方法https://github.com/baidu/lac，编译成功后把头文件和.a文件的路径加入baidu/senta的cmakelist.txt中即可。
