### ISSUE TITLE
发现了一个小bug，已修改

### ISSUE THREAD

**Issue by noletter** [baidu/Senta#27]
环境：windows下测试中文的ernie_1.0_skep_large_ch模型。
文件位置：senta/data/vocabulary.py
报错：UncodeDecodeError:'gbk' codec can't decode byte
行数: 30
代码：file_vocab = open(self.vocab_path)
改为：file_vocab = open(self.vocab_path, encoding='utf8')
即可修复。

**Comment by xfcygaocan** [comment]
谢谢，已修复

**Comment by mengxj08** [comment]
@xfcygaocan pip里的senta这里还有bug，尚未和github同步
