### ISSUE TITLE
无法正常使用（Please compile with MKLDNN first to use MKLDNN）

### ISSUE THREAD

**Issue by ou-bing** [baidu/Senta#44]
OS：macOS catalina 10.15.6 (19G73)
Python：3.7.8

`from senta import Senta`
`my_senta = Senta()`
`use_cuda =False`
`my_senta.init_model(model_class="ernie_1.0_skep_large_ch", task="sentiment_classify", use_cuda=use_cuda)`

提示：E0910 08:57:15.549779 135937472 analysis_config.cc:190] Please compile with MKLDNN first to use MKLDNN

我用 `brew install mkl-dnn` 后还是提示这个错误。

**Comment by tongchuchu** [comment]
请问这个问题解决了吗？我也遇到了一毛一样的问题

**Comment by ou-bing** [comment]
> 请问这个问题解决了吗？我也遇到了一毛一样的问题

没解决，建议使用docker镜像
