### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by mysalter** [baidu/Senta#49]
安装的过程报错，请问是咋回事
 ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xiaomililkx\\AppData\\Local\\Temp\\pip-install-0qhpg_2d\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\xiaomililkx\\AppData\\Local\\Temp\\pip-install-0qhpg_2d\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xiaomililkx\AppData\Local\Temp\pip-pip-egg-info-_cj1cx2r'
         cwd: C:\Users\xiaomililkx\AppData\Local\Temp\pip-install-0qhpg_2d\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xiaomililkx\AppData\Local\Temp\pip-install-0qhpg_2d\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "c:\python38\lib\codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by biggerbiggest** [comment]
你解决了吗？

**Comment by mysalter** [comment]
> 你解决了吗？

并没有……

**Comment by V1ki** [comment]
直接使用 `pip install Senta` 的话，是不能安装成功的，可以将源码下载下来后，将setup.py 中的`install_requires` 改为下面的值：
```python
install_requires=[
        "nltk == 3.4.5", 
        "numpy == 1.14.5",
        "six == 1.11.0",
        "scikit-learn >= 0.20.4",
        "sentencepiece >= 0.1.83"],
```
其实之所以报错是因为 ` sentencepiece` 的0.1.83 版本的安装出了问题。

**Comment by mysalter** [comment]
> 直接使用 `pip install Senta` 的话，是不能安装成功的，可以将源码下载下来后，将setup.py 中的`install_requires` 改为下面的值：
> 
> ```python
> install_requires=[
>         "nltk == 3.4.5", 
>         "numpy == 1.14.5",
>         "six == 1.11.0",
>         "scikit-learn >= 0.20.4",
>         "sentencepiece >= 0.1.83"],
> ```
> 
> 其实之所以报错是因为 ` sentencepiece` 的0.1.83 版本的安装出了问题。

特别感谢

**Comment by SoulSubmerge** [comment]
> 直接使用 `pip install Senta` 的话，是不能安装成功的，可以将源码下载下来后，将setup.py 中的`install_requires` 改为下面的值：
> 
> ```python
> install_requires=[
>         "nltk == 3.4.5", 
>         "numpy == 1.14.5",
>         "six == 1.11.0",
>         "scikit-learn >= 0.20.4",
>         "sentencepiece >= 0.1.83"],
> ```
> 
> 其实之所以报错是因为 ` sentencepiece` 的0.1.83 版本的安装出了问题。

我这样安装还是依旧报错，这是为什么呢？

**Comment by SoulSubmerge** [comment]
Downloading scipy-1.5.4-cp37-cp37m-win_amd64.whl (31.2 MB)
每次都是下载这个的时候出错
